engines:
  tailor:
    enabled: true
    checks:
      trailing_whitespace:
        enabled: false
      terminating-newline:
        enabled: false
  fixme:
    enabled: true
  spellcheck:
    enabled: true

ratings:
  paths:
  - "**.swift"
