language: objective-c
osx_image: xcode8.2
script:
  - xcodebuild -version
  - xcodebuild -scheme Nursing -workspace Nursing.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=10.1' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)