language: objective-c
osx_image: xcode8.2

#install:
#  - brew update && brew install tailor

# Based on .travis.yml from SwiftMoment repo
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Nursing.xcworkspace
  - IOS_APP_SCHEME="Nursing"
  - IOS_FRAMEWORK_SCHEME="NursingCommon"
  - IOS_SDK=iphonesimulator10.2
  matrix:
    - DESTINATION="OS=10.1,name=iPhone 7 Plus"     SCHEME="$IOS_APP_SCHEME"           SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=10.1,name=iPhone 7 Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="NO" POD_LINT="NO"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build schemes in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build
    fi

  # Build schemes in Release
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi

after_success:
  # Send coverage data
  - bash <(curl -s https://codecov.io/bash) -J 'Nursing '
